<script>
	import ResultsRow from './ResultsRow.svelte';
	import { goto } from '$app/navigation'
	import { page } from '$app/stores';

	import schemes from '$lib/assets/schemes.json';
	import { flattenedSchemeIndex } from '$lib/flattenedSchemes.js';
	import Fuse from 'fuse.js';
	import "@picocss/pico";
	import Pagination from './Pagination.svelte';

	// Flatten the scheme
	const flatSchemes = flattenedSchemeIndex(schemes);

	const fuseOptions = {
		isCaseSensitive: false,
		keys: ['schemeName', 'ampliconSize']
	};

	export let data;

	// Set the filter checkbox values
	let showStatus = {
		'withdrawn': true,
		'deprecated': true,
		'draft': true,
		'autogenerated': true,
		'tested': true,
		'validated': true
	}
	// Wanted Status



	let query = data.query;

	let pageNum = data.pageNum; // set a page number
	
	const fuse = new Fuse(flatSchemes, fuseOptions);
	$: flatSearchResult = query.trim().length ? fuse.search(query)  : flatSchemes.map(
        (item, index) => ({
          item,
          refIndex: index,
          matches: [],
          score: 1,
        }),
      );

	// Pages
	const pageSize = 25;
	$: pageIndex = pageNum -1;
	$: pageCount = Math.ceil(flatSearchResult.length / pageSize);

	$: filtFlatSearchResult = flatSearchResult.filter((item) => {
		return showStatus[item.item.status];
	});

	$: searchResult = filtFlatSearchResult.slice(
		pageIndex * pageSize,
		pageIndex * pageSize + pageSize,
	);



	let timer;
	const debouncedSubmit = async () => {
		clearTimeout(timer);
		timer = setTimeout(onSubmit, 250);
	}

	$: if (pageNum > pageCount){
		pageNum = pageCount;
	  }
	
	let onSubmit = async () => {
      let navSearchQuery = $page.url.searchParams.get('q') || '';
	  let navPageNum = $page.url.searchParams.get('pageNum') || 1;
	  
      if (query.trim() == navSearchQuery.trim() && pageNum == navPageNum.trim()) // don't navigate if the query is the same
        return
	
      await goto(query.trim().length ? `/?q=${encodeURIComponent(query.trim())}&pageNum=${pageNum}` : `/?pageNum=${pageNum}`, {
        keepFocus: true
      })
    }


</script>

<h1>Schemes</h1>

<h4>Search</h4>
<form on:submit|preventDefault={onSubmit}>
	<input type="text" bind:value={query} on:keyup={debouncedSubmit} />	
</form>

<details>
	<summary>Advanced Search</summary>
	{#each Object.entries(showStatus) as [status, value]}
			<label>
				<input type="checkbox" bind:checked={showStatus[status]} />
				Show {status}
			</label>
	{/each}
  </details>


{#if searchResult.length > 0}
<table role='grid'>
		<!-- <tr>
			<th>Scheme name</th>
			<th>Amplicon size</th>
			<th>Version</th>
			<th>Status</th>
		</tr> -->
		<hr>
		{#each searchResult as result}
		<ResultsRow scheme={result.item} query={query} />
		{/each}
	</table>
{:else}
	<p>No results</p>
{/if}
<Pagination pageCount={pageCount} pageNum={pageNum} resultCount={flatSearchResult.length} pageSize={searchResult.length} query={query}/>
	
<style>
details {
	color: #00444D;
}
label:hover {
	color:#810081;
}
</style>


