<script>
    export let scheme;
	export let query;
</script>

<tr>
    <td><a href={`/detail/${scheme.schemename}/${scheme.ampliconsize}/${scheme.schemeversion}?query=${query}`}>{scheme.schemeName}</a></td>
    <td>{scheme.ampliconsize}</td>
	<td>{scheme.schemeversion}</td>
    <td><span class='pill {scheme.status}'><b>{scheme.status}</b></span></td>
</tr>


<style>
	.pill {
		display: block;
		border-radius: 0.5em;
		padding: 0.5em;
		text-align: center;

	}
	.pill.draft {
		background-color: #e28a2b;
		color: #ffffff;
	}
	.pill.autogenerated {
		background-color: #e28a2b;
		color: #ffffff;
	}
	.pill.deprecated {
		background-color: #e28a2b;
		color: #ffffff;
	}
	.pill.withdrawn {
		background-color: #ea1111;
		color: #ffffff;
	}
	.pill.tested {
		background-color: #1127cf;
		color: #ffffff;
	}
	.pill.validated {
		background-color: #0c9600;
		color: #ffffff;
	}
</style>