<script>
    export let scheme;
	export let query;
</script>


<!-- <tr>
	<td><a href={`/detail/${scheme.schemename}/${scheme.ampliconsize}/${scheme.schemeversion}?q=${query}`}>{scheme.schemeName}</a></td>
	<td>{scheme.ampliconsize}</td>
	<td>{scheme.schemeversion}</td>
	<td><span class='pill {scheme.status}'><strong>{scheme.status}</strong></span></td>
</tr> -->

<main class="container">
	<nav>
		<ul><a href={`/detail/${scheme.schemename}/${scheme.ampliconsize}/${scheme.schemeversion}?q=${query}`}><strong>{scheme.schemename} / {scheme.ampliconsize} / {scheme.schemeversion}</strong></a></ul>
		<ul><span class='pill {scheme.status}'><strong>{scheme.status}</strong></span></ul>
	</nav>
	<aside>
	<nav>
		<ul><b>authors:</b> {scheme.authors} </ul>

	</nav>
	</aside>
	<nav>
		<ul><b>species:</b>{scheme.species} </ul>
		<ul style="color:grey">{scheme.license} </ul>

	</nav>





</main>
<hr>



<style>
	.ol {
		text-indent: 25px;
	}

	.container strong {
		font-size: 1.5em;
	}
	.container a{
		color:#00444D;
		background-color: transparent;
	}
	.container a:hover{
		color:#810081;
		background-color: transparent;
		text-decoration: underline;
		transition: 0.2s;
	}
	.pill {
		display: block;
		border-radius: 0.3em;
		padding: 0.5em;
		text-align: center;
	}
	.pill strong {
		font-size: 1em;
	}
	.pill.draft {
		background-color: #5e4b56;
		color: #ffffff;
	}
	.pill.autogenerated {
		background-color: #b9c6ae;
		color: #ffffff;
	}
	.pill.deprecated {
		background-color: #b9c6ae;
		color: #ffffff;
	}
	.pill.withdrawn {
		background-color: #f2605d;
		color: #ffffff;
	}
	.pill.tested {
		background-color: #5899E2;
		color: #ffffff;
	}
	.pill.validated {
		background-color: #499f68;
		color: #ffffff;
	}
</style>