<main>
    <h1>FAQs</h1>

    <details open>
        <summary>What does scheme status mean?</summary>
        <ul>
            <li><span class='pill withdrawn'><b>withdrawn</b></span>This scheme that has been withdrawn, due to any reason. ie poor performance</li>
            <li><span class='pill deprecated'><b>deprecated</b></span>This scheme is no longer maintained. Often surpassed by a newer version</li>
            <li><span class='pill autogenerated'><b>autogenerated</b></span>This scheme is generated from data sources public databases using pathogen agnostic pipelines</li>
            <li><span class='pill draft'><b>draft</b></span>This is a curated scheme, however has not undergone any testing. We hope schemes will either progress to tested/valdated or deprecated/withdrawn</li>
            <li><span class='pill tested'><b>tested</b></span>This scheme has undergone small scale testing, ie shown to work against small number of samples</li>
            <li><span class='pill validated'><b>validated</b></span>The highest level of validation. The scheme should have undergone extensive use and validation. Often used in public health, or has citations </li>
          </ul>
    </details>

</main>

<style>
	.pill {
        width:15%;
		display: block;
		border-radius: 0.5em;
		padding: 0.5em;
		text-align: center;
        

	}
	.pill.draft {
		background-color: #e28a2b;
		color: #ffffff;
	}
	.pill.autogenerated {
		background-color: #e28a2b;
		color: #ffffff;
	}
	.pill.deprecated {
		background-color: #e28a2b;
		color: #ffffff;
	}
	.pill.withdrawn {
		background-color: #ea1111;
		color: #ffffff;
	}
	.pill.tested {
		background-color: #1127cf;
		color: #ffffff;
	}
	.pill.validated {
		background-color: #0c9600;
		color: #ffffff;
	}
</style>